### ISSUE TITLE
fungsi # sebelum parameter ?

### ISSUE THREAD

**Issue by idetips** [riedayme/Blogger#1]
kenapa ada # sebelum parameter ? itu fungsinya apa , apakah memang disengaja dibuat seperti itu ?

https://demosafeplatinum.blogspot.com/2018/01/forex-invest-future-life.html**#**?o=bc31ca8272c1e61793bbc9542819cc4d69026e8dc20d63759960e6c169237be1185aa16b2661fb412d75f3cf7c24a93540d42f2fb4da15d5

**Comment by riedayme** [comment]
sengaja itu om maaf nih baru balas 2022 karena sudah lama tidak buka kode
