### ISSUE TITLE
[ REQUEST ] Mediumish

### ISSUE THREAD

**Issue by sunuazizrahayu** [riedayme/Blogger#6]
masukan untuk template mediumish:

1. Lazyload tetap men-load gambar yang berada pada layar.
untuk sekarang lazyload akan men-load gambar apabila ada aktivitas scroll pada page.

2. untuk CSS post-list dibuat seperti sebelumnya saja, thumbnail akan terlihat berbeda antar postingan apabila resolusinya lebih kecil. bisa dilihat di [blog saya](http://www.kangsunu.web.id)

terimakasih sebelumnya gan @riedayme

**Comment by riedayme** [comment]
okeeeeeeh hehehe

>

**Comment by riedayme** [comment]
yes
