### ISSUE TITLE
Bug di V 1.4

### ISSUE THREAD

**Issue by faizcaster** [riedayme/Blogger#8]
Halo, mau nambahin perbaikan dikit nih, kalo bisa di V 1.4 dengan nama file **template.xml** pas di pasang di Blogger, tidak bisa untuk di setting untuk bagian Mobile template nya. Jadi gak muncul gambar **Gear** atau **Settings** pada tampilan Mobile, semoga bisa di fix. Terima kasih

**Comment by riedayme** [comment]
yess
